name: Release

on:
  push:
    branches:
      - 'kmm'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build
        run: ./gradlew sdk-for-kmm:assemble --stacktrace -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Release library
        run: ./gradlew sdk-for-kmm:publish -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}